# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

FROM git.opentalk.dev:5050/opentalk/backend/containers/rust:1.94.1-alpine AS builder

RUN apk add ca-certificates

ARG GIT_SHA
ARG GIT_REF
ARG VERGEN_GIT_SHA=$GIT_SHA
ARG VERGEN_GIT_BRANCH=$GIT_REF

RUN mkdir /smtp-mailer
WORKDIR /smtp-mailer

COPY ./build.rs .
COPY ./src ./src
COPY ./Cargo.* .
COPY ./resources ./resources

RUN cargo auditable build --release --locked --package opentalk-smtp-mailer --target=x86_64-unknown-linux-musl

FROM scratch

WORKDIR /opt/smtp-mailer

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /smtp-mailer/target/x86_64-unknown-linux-musl/release/opentalk-smtp-mailer .
COPY ./resources ./resources

ENV USERID=1000
ENV GROUPID=1000
USER $USERID:$GROUPID

CMD ["/opt/smtp-mailer/opentalk-smtp-mailer"]
