# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

---
image: git.opentalk.dev:5050/opentalk/backend/containers/rust:1.82.0-bookworm

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  KANIKO_IMAGE: gcr.io/kaniko-project/executor:debug

stages:
  - lint
  - test
  - build
  - package
  - trigger

.default_job_condition: &default_job_condition
  needs: []
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'

lint:fmt:
  stage: lint
  <<: *default_job_condition
  script:
    - cargo +nightly fmt -- --check

lint:clippy:
  stage: lint
  <<: *default_job_condition
  script: cargo clippy --workspace --all-features --tests -- --deny warnings

lint:doc:
  variables:
    RUSTDOCFLAGS: -Dwarnings
  stage: lint
  <<: *default_job_condition
  script: cargo doc --workspace --no-deps

lint:dependency_check:
  stage: lint
  <<: *default_job_condition
  script: cargo deny check

lint:licensing:
  stage: lint
  <<: *default_job_condition
  image:
    name: fsfe/reuse:latest
    entrypoint: ['']
  script:
    - reuse lint

lint:yaml:
  stage: lint
  <<: *default_job_condition
  image: alpine:3.20
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

lint:toml:
  stage: lint
  <<: *default_job_condition
  script: taplo fmt --check

lint:markdown:
  stage: lint
  <<: *default_job_condition
  image: registry.gitlab.com/pipeline-components/markdownlint:latest
  script:
    - mdl --style .markdown_style.rb  --warnings .

lint:commit:
  allow_failure: true
  cache: {}
  image: node:lts-alpine
  stage: lint
  <<: *default_job_condition
  before_script:
    - apk add --no-cache git
    - npm install -g @commitlint/cli @commitlint/config-conventional
  script:
    - npx commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to HEAD --verbose

lint:justfile:
  stage: lint
  <<: *default_job_condition
  before_script: if ! just --version; then cargo install just; fi
  script:
    # The `--fmt` command-line parameter is still unstable, but valuable anyway.
    - just --unstable --fmt --check

test:cargo_test:
  stage: test
  <<: *default_job_condition
  before_script:
    - rustup component add rustfmt
  script:
    - cargo test --workspace --locked

package:mailer-container-mr:
  stage: package
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  image:
    name: $KANIKO_IMAGE
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    # According to https://docs.docker.com/engine/reference/commandline/tag/
    # the tag may contain lowercase and uppercase letters, digits, underscores,
    # periods, and hyphens, so we replace everything else by '_'. It cannot start
    # with a period or hyphen, so we replace those if we find them at the start of a line.
    # It must be no longer than 128 characters, so we truncate it in addition.
    #
    # tr -c means the same as --complement, but busybox tr doesn't have that
    - >
      IMAGE_TAG=$(
          echo -n "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" |
          tr -c '[:alnum:]_.-' '_' |
          sed 's/^[.-]/_/' |
          cut -c -128
      )
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/container/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$IMAGE_TAG
      --force

package:mailer-container-dev:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --build-arg=GIT_SHA=$CI_COMMIT_SHA
      --build-arg=GIT_REF=$CI_COMMIT_REF_NAME
      --dockerfile $CI_PROJECT_DIR/container/Dockerfile
      --destination $CI_REGISTRY_IMAGE:dev
      --force

trigger-docs:
  needs: []
  stage: trigger
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_NAME !~ /^.*canary$/ || $CI_COMMIT_TAG =~ /^v.*$/
  trigger:
    project: opentalk/backend/docs

package:mailer-container-tag:
  rules:
    - if: $CI_COMMIT_TAG != null
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --build-arg=GIT_SHA=$CI_COMMIT_SHA
      --build-arg=GIT_REF=$CI_COMMIT_REF_NAME
      --dockerfile $CI_PROJECT_DIR/container/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --force

package:read-latest-tag:
  rules:
    - if: $CI_COMMIT_TAG != null
  image:
    name: alpine/git
    entrypoint: ['']
  stage: package
  script:
    - git fetch --tags
    - LATEST_TAG=$(git tag --list | grep "^v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+$" | sort -V | tail -n1)
    - echo "LATEST_TAG=$LATEST_TAG" >> package.env
  artifacts:
    reports:
      dotenv: package.env

package:mailer-container-latest:
  rules:
    - if: $CI_COMMIT_TAG != null
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  needs:
    - package:read-latest-tag
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - |
      if [ "$CI_COMMIT_TAG" == "$LATEST_TAG" ]; then
        /kaniko/executor \
          --registry-mirror=mirror.gcr.io \
          --context $CI_PROJECT_DIR \
          --dockerfile $CI_PROJECT_DIR/container/Dockerfile \
          --destination $CI_REGISTRY_IMAGE:latest \
          --force
      fi
