image: git.heinlein-video.de:5050/heinlein-video/rust:1.60

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test
  - build
  - package

lint:fmt:
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  stage: lint
  script:
    - cargo fmt -- --check

lint:clippy:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  stage: lint
  script: cargo clippy --workspace --all-features --tests -- --deny warnings

lint:doc:
  variables:
    RUSTDOCFLAGS: -Dwarnings
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  stage: lint
  script: cargo doc --workspace --no-deps

lint:dependency_check:
  image: git.heinlein-video.de:5050/heinlein-video/cargo-deny:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  stage: lint
  script: cargo-deny check

test:cargo_test:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  stage: test
  before_script:
    - rustup component add rustfmt
  script:
    - cargo test --workspace --locked

package:controller-container:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG != null
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --build-arg=GIT_SHA=$CI_COMMIT_SHA
      --build-arg=GIT_REF=$CI_COMMIT_REF_NAME
      --dockerfile $CI_PROJECT_DIR/container/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --destination $CI_REGISTRY_IMAGE:latest
      --force
